# Generated by Django 3.1.3 on 2020-11-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='campaign_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
